import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function CopyPage() {
  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold">Ad Copy</h2>
          <p className="text-sm text-muted-foreground">
            AI-generated ad copy variations powered by Claude Opus
          </p>
        </div>
        <Button>Generate Copy</Button>
      </div>

      {/* Empty State */}
      <Card>
        <CardContent className="flex flex-col items-center justify-center py-16">
          <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-muted">
            <svg className="h-8 w-8 text-muted-foreground" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
            </svg>
          </div>
          <h3 className="mb-2 text-lg font-semibold">No Copy Generated Yet</h3>
          <p className="mb-6 max-w-md text-center text-sm text-muted-foreground">
            Generate creative briefs first, then create ad copy variations for each
            brief. Copy is generated by Claude Opus for maximum quality.
          </p>
          <Button>Generate Copy</Button>
        </CardContent>
      </Card>
    </div>
  );
}
