import type { Job } from "bullmq";
import { generateAnalysis, generateAdCopy, generateStructured } from "@doemedia/ai";
import { AI_MODELS } from "@doemedia/shared";

export interface GenerateStrategyData {
  clientId: string;
  clientName: string;
  industry: string;
  brandVoice: string;
  targetAudience: string;
  performanceData: string; // Serialized performance summary
}

/**
 * Worker job: Generate a full creative strategy for a client.
 * This is the core AI pipeline that runs the 4-stage process:
 * 1. Analyze performance data (Sonnet)
 * 2. Generate strategy (Sonnet)
 * 3. Generate format-specific briefs (Opus)
 * 4. Generate ad copy for each brief (Opus)
 */
export async function generateStrategy(job: Job<GenerateStrategyData>) {
  const { clientId, clientName, industry, brandVoice, targetAudience, performanceData } =
    job.data;

  console.log(`Generating strategy for ${clientName}...`);

  // Stage 1: Performance Analysis
  await job.updateProgress(10);
  const analysisSystem = `You are a Meta ads performance analyst specializing in e-commerce brands in the ${industry} industry. You analyze ad creative performance data and identify actionable patterns.`;

  const analysisPrompt = `Analyze the following performance data for ${clientName} and identify:
1. Top 3 winning creative patterns (format + hook + angle combos with best ROAS)
2. Top 3 losing patterns to avoid
3. Creative fatigue signals (ads with declining performance)
4. Format distribution gaps
5. Recommendations for the next creative cycle

Performance Data:
${performanceData}`;

  const analysis = await generateAnalysis(analysisPrompt, analysisSystem);
  await job.updateProgress(30);

  // Stage 2: Strategy Generation
  const strategySystem = `You are a creative strategist for a performance marketing agency managing Meta ads for e-commerce Shopify brands. You create data-driven creative strategies.`;

  const strategyPrompt = `Based on this performance analysis for ${clientName} (${industry}):

${analysis}

Brand Voice: ${brandVoice}
Target Audience: ${targetAudience}

Generate a creative strategy with:
1. Strategic overview (2-3 sentences)
2. 6-8 recommended briefs, each specifying format (IMAGE/VIDEO/CAROUSEL), hook concept, angle, and why
3. Framework for static briefs (visual concept + headline approach)
4. Framework for video briefs (hook -> meat -> action/offer structure)
5. What to pause/kill from current rotation`;

  const strategy = await generateAdCopy(strategyPrompt, strategySystem);
  await job.updateProgress(60);

  // Stage 3 & 4: Brief + Copy generation would follow here
  // Each brief gets 3-5 copy variants generated by Opus
  await job.updateProgress(100);

  console.log(`Strategy generated for ${clientName}`);

  return {
    clientId,
    analysis,
    strategy,
    // TODO: Store in creative_strategies, creative_briefs, ad_copy_variants tables
  };
}
